name = "santafresh-worker"
main = "src/index.ts"
compatibility_date = "2024-09-02"
[vars]
OPENAI_BASE = "https://api.openai.com"
OPENAI_MODEL = "gpt-5"
OPENAI_TTS_MODEL = "gpt-5-tts"
OPENAI_VOICE = "alloy"
[observability]
enabled = true
