name: Deploy Cloudflare Worker
on:
  push:
    branches: [ main ]
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Wrangler
        run: npm i -g wrangler@3.78.10
      - name: Whoami
        run: wrangler whoami --api-token "$CF_API_TOKEN" --account-id "$CF_ACCOUNT_ID"
      - name: Ensure workers.dev subdomain
        run: wrangler subdomain set "${{ github.repository_owner }}" --api-token "$CF_API_TOKEN" --account-id "$CF_ACCOUNT_ID" || true
      - name: Put OPENAI_API_KEY secret
        working-directory: worker
        run: echo -n "$OPENAI_API_KEY" | wrangler secret put OPENAI_API_KEY --api-token "$CF_API_TOKEN" --account-id "$CF_ACCOUNT_ID" --yes
      - name: Publish Worker
        working-directory: worker
        run: wrangler publish --api-token "$CF_API_TOKEN" --account-id "$CF_ACCOUNT_ID" --minify
